// Code generated by go generate; DO NOT EDIT.

package enums

type COUNTRY int

const (
	JPN COUNTRY = iota
	US  COUNTRY = iota
	UK  COUNTRY = iota
)

func (e COUNTRY) String() string {
	switch e {
	case JPN:
		return "Japan"
	case US:
		return "United States"
	case UK:
		return "United Kingdom"
	default:
		return "Unknown COUNTRY"
	}
}
