// Code generated by go generate; DO NOT EDIT.

package enums


type COUNTRY int


const (
        JPN COUNTRY = iota
        US COUNTRY = iota
        UK COUNTRY = iota
)

func (e COUNTRY) String() string {
    switch e {
	case JPN:
		return &#34;Japan&#34;
	case US:
		return &#34;United States&#34;
	case UK:
		return &#34;United Kingdom&#34;
    default:
        return "Unknown COUNTRY"
    }
}
