// Code generated by go generate; DO NOT EDIT.

package types

type CITY int

const (
	TYO CITY = iota
	NYC CITY = iota
	LDN CITY = iota
)

func (e CITY) String() string {
	switch e {
	case TYO:
		return "Tokyo"
	case NYC:
		return "New York"
	case LDN:
		return "London"
	default:
		return "Unknown CITY"
	}
}
