// Code generated by go generate; DO NOT EDIT.

package types


type CITY int


const (
        TYO CITY = iota
        NYC CITY = iota
        LDN CITY = iota
)

func (e CITY) String() string {
    switch e {
	case TYO:
		return &#34;Tokyo&#34;
	case NYC:
		return &#34;New York&#34;
	case LDN:
		return &#34;London&#34;
    default:
        return "Unknown CITY"
    }
}
