// Code generated by gogen; DO NOT EDIT.

package driver

import "context"

type UserDriver interface {
	Insert(ctx context.Context, target *entity.User) error
	Find(ctx context.Context, id string) (*entity.User, error)
	Update(ctx context.Context, target *entity.User) error
	Delete(ctx context.Context, target *entity.User) error
}
